services:
  - type: web
    name: reciclaje-fastapi
    env: python
    plan: free
    region: oregon
    buildCommand: |
      pip install -r app/requirements.txt
      python app/bootstrap_model.py
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: GDRIVE_FILE_ID
        value: "1-8eWeo-y5mIY0stNGBZCcYC_zNrKIbID"
